### PR TITLE
91 JSON Schema

### PR DESCRIPTION
**Pull request by pixie79**
Add JSON Schema Import function and extend export.

Currently import does not handle $ref (not sure what we want to do there)

Export does not export definitions (could not see where to extend that bit)

### CODE REVIEW

**Comment by pixie79** [comment]
This is to fix issue #91

**Comment by simonharrer** [comment]
Thanks for this PR! Looks fine, but let's exclude the definitions here for now as this needs discussion.

1. The reference mechanism of JSON schema differs from Data Contract Specification.
2. The Data Contract Specification currently does not support the allOf/oneOf/anyOf logic of JSON schema.

Let's discuss each of those separately.

Regarding 1: Without the allOf/oneOf/anyOf logic, we could implement an import that makes use of the definitions in DCS. We could use the $ref mechanism to link to the referenced definition. No problem here. The difference, however, is that one can override the fields (in JSON schema, you cannot). But this should not be an issue here, but more an issue when you'd do an export to JSON schema when using $ref.

Regarding 2: We could support this with `config` options, e.g., like this:
```yaml
models:
  my-model:
    config:
      jsonSchemaAllOf:
        - ref1
        - ref2
```

**Comment by pixie79** [comment]
Agreed, I just mentioned it as something that needs to be handled in the future so that it did not get lost. Happy to leave as is for now while a debate happens as to the best options.

**Comment by simonharrer** [comment]
Sure, thanks for the great PR. I've created an issue to track the discussion around the discovered issues.

**Pull request merged**
