### PR TITLE
Fix/311: Add enum and map type for avro schema

### PR DESCRIPTION
**Pull request by aniketkapdule**
- [x] Tests pass
- [x] ruff format
- [x] CHANGELOG.md entry added

Resolves issue #311 

This PR adds enum and map type logic to the import avro_importer.py, resolving import errors.

### CODE REVIEW

**Comment by simonharrer** [comment]
There currently is no `map` data type in the spec. https://datacontract.com/#data-types 

@jochenchrist three options: 
1. follow JSON Schema: type `object` with `additionalProperties` where one can define the types of the values
2. follow Avro Schema: introduce a dedicated data type `map` with `values` field to define the substructures
3. no map type at all

Not sure where we should be heading. Any thoughts?

**Comment by jochenchrist** [comment]
Created https://github.com/datacontract/datacontract-specification/issues/80 to discuss map

**Comment by aniketkapdule** [comment]
@jochenchrist Correct me if I am wrong, but I don't see any discussion about enum type. Should I raise a PR to also add "enum" in the [`FieldType`](https://github.com/datacontract/datacontract-specification/blob/0efe7adf08580a9a445faa438b11d107a2e458f1/datacontract.schema.json#L1475)?

**Comment by jochenchrist** [comment]
Regarding `enum`: I would prefer not to include enum as a logical data type in the specification. Such a data type is very rare. We have a property enum that we can use for this purpose, and we can set it accordingly during import and export.

**Comment by jochenchrist** [comment]
Like this:

```
      status:
        type: string
        required: true
        description: order status
        enum:
            - PLACED
            - SHIPPED
            - DELIVERED
            - CANCELLED
        config:
          avroType: enum
```

**Comment by aniketkapdule** [comment]
@jochenchrist I have made appropriate changes to accommodate `enum` type, as you have mentioned above, I will remove the changes from `datacontract/lint/schema.py` regarding `map` type once [this](https://github.com/datacontract/datacontract-specification/issues/80) issue is closed and pr is merged.

**Comment by jochenchrist** [comment]
Thank you for your contribution.

We added official support for Maps to the specification. 🎉
Also notice the new properties `keys` and `values`.

**Comment by jochenchrist** [comment]
I also updated the code, resolved merge conflicts, and removed the workaround in datacontract/lint/schema.py

**Comment by aniketkapdule** [comment]
> I also updated the code, resolved merge conflicts, and removed the workaround in datacontract/lint/schema.py

Thank you @jochenchrist, Looking forward to do more contributions 👍

**Pull request merged**
