### PR TITLE
feat: add array and struct field management in glue importer

### PR DESCRIPTION
**Pull request by pierre-monnet**
For now when Glue table contains array or struct field, it is returned as "variant" and items or subfields aren't retrieve.

### CODE REVIEW

**Review by massilchabane — APPROVED** [review]
Will be really useful to us ! :)

**Comment by jochenchrist** [comment]
Great contribution. LGTM.

**Comment by jochenchrist** [comment]
Please check the test results

**Comment by pierre-monnet** [comment]
> Please check the test results
oops i made some typos in my test case and expected result, I fixed them

**Comment by jochenchrist** [comment]
Merged, again, thanks for your contribution.

Do you need are quick release for this feature?

**Comment by simonharrer** [comment]
@pierre-monnet can you provide a CHANGELOG entry, please? Perhaps in another PR?

**Comment by pierre-monnet** [comment]
> @pierre-monnet can you provide a CHANGELOG entry, please? Perhaps in another PR?

No problem, I'll work on it

**Pull request merged**
