### PR TITLE
add export endpoint to datacontract api

### PR DESCRIPTION
**Pull request by torbenkeller**

### CODE REVIEW

**Comment by torbenkeller** [comment]
Sorry for the amount of files, I had to resetup my venv and it ran`ruff format`

**Comment by jochenchrist** [comment]
> Sorry for the amount of files, I had to resetup my venv and it ran`ruff check --fix` and `ruff format `

OK, I also run `ruff format` on main, can you rebase/merge?

**Comment by torbenkeller** [comment]
@jochenchrist I think your raff format did not respect the line lenght of 120. At least my run did unwrap a few lines

**Comment by jochenchrist** [comment]
> @jochenchrist I think your raff format did not respect the line lenght of 120. At least my run did unwrap a few lines

Thanks, you are correct. My IntelliJ settings on Optimize imports changed the imports afterward 🙈

**Pull request merged**
