### PR TITLE
Add ability to export to go types

### PR DESCRIPTION
**Pull request by pixie79**
#187 

Add the ability to export *go* structs.

This will need extension once the handling of logicalTypes is added.

### CODE REVIEW

**Comment by jochenchrist** [comment]
Thanks for your contribution.
Please add a pytest for this export :)
Also, please run 
`ruff format` to format the code

**Comment by pixie79** [comment]
I have added a test, ideally I will add some more tests to handle all the logical types once it has been decided by the project how these are being handled. At which point I think the test datacontract.yml needs to be more extensive.

**Comment by jochenchrist** [comment]
LGTM.

Only think that surprises me a bit are the json & avro tags. 
What is the rationale behind them?

**Review by jochenchrist — APPROVED** [review]

**Comment by pixie79** [comment]
The reason for the tags is it helps with serialisation of data to/from json. We already know that information from the data contract specification so it helps to add it here. If it is not use by the end user later if does no harm being there, but if they need it then it saves a lot of work :)

**Comment by jochenchrist** [comment]
OK, agree with JSON. Still not quite sure, if Avro is commonly used with Go, but let's see if we get some feedback here. Happy to merge.

**Pull request merged**
