### PR TITLE
Changed input file detection to be recursive

### PR DESCRIPTION
**Pull request by fknierim**
This change enables catalog creation to include datacontracts in subfolders.

### CODE REVIEW

**Comment by simonharrer** [comment]
One could already have it recursively if one used `**/*.yaml` as a global expression. Does one always want to use an rglob expression?

**Comment by simonharrer** [comment]
It seems, powershell automatically expands "**/*.yaml" to "raw_zone\datacontract-testa.yaml raw_zone\datacontract-testb.yaml refined_zone\datacontract-testc.yaml trusted_zone\datacontract-testd.yaml trusted_zone\datacontract-teste.yaml" before invoking the command in the CLI. I am no powershell expert, but is there a way to prevent this?

**Comment by jochenchrist** [comment]
I'd go with `rglob`.
Sounds reasonable that users want data contracts in any subdirectory.

**Comment by simonharrer** [comment]
Ok, fine. :-)

**Pull request merged**
