### PR TITLE
Support Bigquery JSON as export format

### LINKED ISSUE #111: datacontract export --format bigquery
Export to BigQuery schema

### PR DESCRIPTION
**Pull request by jpraetorius**
- have a new exporter for BigQuery JSON Files
- hook it up to the CLI
- simplify the checking for model selection during export

Closes #111

### CODE REVIEW

**Comment by simonharrer** [comment]
The bigquery json file is wrong. The schema has an array of fields, not a map with named fields.

**Comment by simonharrer** [comment]
Can you add an entry in the CHANGELOG.md as well?

**Comment by simonharrer** [comment]
Can you resolve the conflicts? Then we should be good to go.

**Comment by jpraetorius** [comment]
Just gave that a shot :)

**Comment by simonharrer** [comment]
It seems the tests are failing still. Can you have another look, please? And thanks for all the hard work! :-)

**Comment by jpraetorius** [comment]
Seems as if things took a while, but now are all green?

**Pull request merged**
